### ISSUE TITLE
server fails to startup with plugin installed

### ISSUE THREAD

**Issue by sdubrul** [devpi/devpi-jenkins#5]
`$ devpi-server --host 0.0.0.0 --port 4040 --serverdir /srv/devpi/
Traceback (most recent call last):
  File "/usr/local/bin/devpi-server", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/devpi_server/main.py", line 54, in main
    pluginmanager = get_pluginmanager()
  File "/usr/local/lib/python2.7/dist-packages/devpi_server/config.py", line 24, in get_pluginmanager
    pm.load_setuptools_entrypoints("devpi_server")
  File "/home/sdubrul/.local/lib/python2.7/site-packages/pluggy.py", line 504, in load_setuptools_entrypoints
    self.register(plugin, name=ep.name)
  File "/home/sdubrul/.local/lib/python2.7/site-packages/pluggy.py", line 369, in register
    self._verify_hook(hook, hookimpl)
  File "/home/sdubrul/.local/lib/python2.7/site-packages/pluggy.py", line 477, in _verify_hook
    _formatdef(hookimpl.function), ", ".join(hook.argnames)))
pluggy.PluginValidationError: Plugin 'devpi-jenkins'
hook 'devpiserver_on_upload_sync'
argument 'projectname' not available
plugin definition: devpiserver_on_upload_sync(log, application_url, stage, projectname, version)
available hookargs: __multicall__, log, application_url, stage, project, version`

`sdubrul@sdubrul-us:~$ pip list | grep devpi
devpi-client (2.5.0)
devpi-common (2.0.8)
devpi-server (3.0.2)
devpi-web (3.0.0)
sdubrul@sdubrul-us:~$`

**Comment by fschulze** [comment]
I have release 2.0.0 to fix that.

**Comment by sdubrul** [comment]
Right. Pip installed & the new version allows startup of devpi-server.
Thanks mate!
/Stijn
